version: '3'

volumes:
  freezing-data:
    external: true

services:

 db:
  image: mysql:5.7
  container_name: freezing-db
  ports:
    - "3306:3306"
  volumes:
    - freezing-data:/var/lib/mysql
    - ./docker/db/sql-scripts:/sql
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-fr33z3}
    MYSQL_DATABASE: ${MYSQL_DATABASE:-freezing}
    MYSQL_USER: ${MYSQL_USER:-freezing}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD:-zeer0}

 web:
   build: .
   container_name: web
   command: bafs-server
   ports:
     - "5000:5000"
   volumes:
     - ./data:/data
     - ./resources/docker/settings.cfg:/config/settings.cfg
   links:
     - db:db.container
